name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
     - completed

jobs:
  CD:
    name: entrega continua
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success'}}

    steps:
      - name: Checkout repository
        uses: action/checkout@v3

      
        

    